In [1]:
import torch

In [2]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
print(x.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [3]:
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [4]:
print(x.is_leaf, y.is_leaf)

True False


In [7]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
None


In [6]:
a = torch.tensor([1,2,3])
print(a.mean(dtype=torch.float64))

tensor(2., dtype=torch.float64)


In [9]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [10]:
out.backward()

In [13]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [14]:
out2 = x.sum()
out2.backward()
print(x.grad)

tensor([[5.5000, 5.5000],
        [5.5000, 5.5000]])


In [12]:
out3 = x.sum()
x.grad.data.zero_()
out3.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]])


In [13]:
# 创建需要梯度的张量
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
print(f"张量 x: {x}")
print(f"requires_grad: {x.requires_grad}")

# 普通张量（不需要梯度）
y = torch.tensor([1.0, 2.0, 3.0], requires_grad=False)
print(f"普通张量: {y.requires_grad}")

张量 x: tensor([1., 2., 3.], requires_grad=True)
requires_grad: True
普通张量: False


In [2]:
# 简单例子
x = torch.tensor(2.0, requires_grad=True)
y = x ** 2 + 3 * x + 1

# 反向传播计算梯度
y.backward()

# 查看梯度 dy/dx = 2x + 3 = 2*2 + 3 = 7
print(f"x 的梯度: {x.grad}")  # tensor(7.)

x 的梯度: 7.0


In [3]:
x = torch.tensor(3.0, requires_grad=True)
y = x ** 3 + x ** 3 + 7 * x + 12

y.backward()
print(x.grad)

tensor(61.)
