In [1]:
import torch
from torch import nn

def corr2d(X, K):
    h, w = K.shape
    Y = torch.zeros((X.shape[0] - h + 1, X.shape[1] - w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            Y[i, j] = (X[i: i+h, j: j+w] * K).sum()
    return Y

In [5]:
X = torch.arange(0, 9).reshape((3,-1))
print(X)
K = torch.arange(0, 4).reshape((2, -1))
print(K)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1],
        [2, 3]])


In [6]:
corr2d(X, K)

tensor([[19., 25.],
        [37., 43.]])

In [ ]:
class Conv2D(nn.Module):
    def __init__(self, kernel_size):
        super(Conv2D, self).__init__()
        self.weight = nn.Parameter(torch.randn(kernel_size))
        self.bias = nn.Parameter(torch.randn(1))

    def forward(self, x):
        return corr2d(x, self.weight) + self.bias

In [8]:
# 图像中物体边缘检测
X = torch.ones(6, 8)
X[:, 2:6] = 0
X

tensor([[1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.]])

In [9]:
K = torch.tensor([[1, -1]])
K.shape

torch.Size([1, 2])

In [10]:
Y = corr2d(X, K)
Y

tensor([[ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.]])

In [3]:
import torch
import torch.nn as nn

x = torch.randn(1, 3, 5, 5)
print(f"输入形状: {x.shape}")

输入形状: torch.Size([1, 3, 5, 5])


In [4]:
conv = nn.Conv2d(in_channels=3, out_channels=6, kernel_size=3, padding=0, stride=1)
y = conv(x)

y

tensor([[[[-0.1155,  0.4837, -0.7314],
          [ 0.5072,  0.3285, -0.2487],
          [ 1.0032, -0.4160, -0.3517]],

         [[-0.3847,  1.0622, -0.5962],
          [-0.9732,  0.5845,  0.3922],
          [ 0.4118, -0.3799,  1.9236]],

         [[ 0.4396, -0.5335,  0.0711],
          [-1.2630,  0.2801, -0.1411],
          [-1.6077,  0.1433,  0.5863]],

         [[-0.4204, -0.0809,  0.0847],
          [ 0.1986, -0.7847,  0.4092],
          [ 0.3250,  0.8250,  1.5492]],

         [[ 0.1403,  1.9171,  0.9821],
          [ 1.2986, -0.6482,  1.8074],
          [ 0.5836, -1.8290, -0.5268]],

         [[ 0.2161,  0.7695, -0.4971],
          [-0.4623, -0.4372,  0.7859],
          [-0.6654, -0.0260, -0.3626]]]], grad_fn=<ConvolutionBackward0>)