In [70]:
import torch.nn as nn
import torch
from PIL import Image
from torchvision.transforms import transforms
import torch.nn.functional as F

In [87]:
class TestConv(nn.Module):
    def __init__(self):
        super(TestConv, self).__init__()
        self.conv1 = nn.Conv2d(3, 5, 3)
        self.conv2 = nn.Conv2d(5, 1, 3)

    def forward(self, x):
        x = F.relu(self.conv1(x))
        return F.relu(self.conv2(x))

In [88]:
x = torch.randn(3 * 5 * 5).reshape((3, 5, 5))
x

tensor([[[-1.5748,  0.1874,  0.7735,  0.7711, -0.1938],
         [-0.8871, -0.1251, -1.6569, -1.1317, -0.6370],
         [ 0.9132, -2.0989,  1.2976,  0.6316,  0.0900],
         [ 1.4537,  0.8803,  0.7863,  1.6548, -0.1400],
         [-0.0337,  0.5412,  0.5396,  1.4009, -1.1015]],

        [[ 0.8059,  3.0305, -0.7170, -1.0243,  0.5940],
         [-0.6376, -0.2589,  0.0493,  0.6206,  0.1284],
         [-1.3968, -0.7602,  0.0909,  0.2941, -0.5891],
         [ 1.7122,  0.2996, -1.1478,  0.7493, -0.8223],
         [ 1.1101,  1.4625,  1.2633,  1.6204,  0.8768]],

        [[-0.3015,  0.4511,  0.1529, -0.0574, -0.3919],
         [ 1.2294,  1.3254, -0.6401, -1.2492, -0.7802],
         [-0.4367, -1.4007, -0.0935, -1.4699,  0.1371],
         [-0.3373,  0.2131,  0.9040,  0.9322,  0.0599],
         [ 0.5391, -0.5127, -0.4385,  0.3299,  0.1899]]])

In [89]:
test = TestConv()
y = test(x)
print(y)

tensor([[[0.]]], grad_fn=<ReluBackward0>)


In [90]:
image = Image.open('../dataset/0Q3A0032.JPG')

image_compose = transforms.Compose([
    transforms.Resize(32),
    transforms.ToTensor()
])
image_r = image_compose(image)
print(type(image_r))
y = test(image_r)
print(y)

<class 'torch.Tensor'>
tensor([[[0.2076, 0.2088, 0.2188,  ..., 0.2035, 0.1971, 0.1977],
         [0.2090, 0.2087, 0.2183,  ..., 0.2037, 0.1961, 0.1979],
         [0.2085, 0.2080, 0.2183,  ..., 0.2034, 0.1956, 0.1977],
         ...,
         [0.1568, 0.1875, 0.2170,  ..., 0.2040, 0.1972, 0.1986],
         [0.2151, 0.2370, 0.2224,  ..., 0.2063, 0.2015, 0.2037],
         [0.2204, 0.2107, 0.2231,  ..., 0.2063, 0.2027, 0.2037]]],
       grad_fn=<ReluBackward0>)
