In [70]:
import torch.nn as nn
import torch
from PIL import Image
from torchvision.transforms import transforms
import torch.nn.functional as F

In [79]:
class TestConv(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 5, 3)
        self.conv2 = nn.Conv2d(5, 1, 3)

    def forward(self, x):
        x = F.relu(self.conv1(x))
        return F.relu(self.conv2(x))

In [82]:
x = torch.randn(3 * 5 * 5).reshape((3, 5, 5))
x

tensor([[[-0.0584,  0.0154,  0.6752, -0.3244, -1.9036],
         [ 0.6330,  0.7666, -0.1006, -1.8640, -0.3865],
         [ 0.1265, -1.8989, -0.3523,  1.6576,  0.3350],
         [ 0.4358, -1.8230,  1.1351,  1.0377,  1.2605],
         [ 1.5498,  0.4854,  0.4878, -0.5721, -0.5611]],

        [[-0.7924, -1.4522,  0.6469,  0.2469,  0.1341],
         [ 1.0419, -0.4619, -0.3665, -0.1709, -0.1954],
         [ 1.7585, -0.5534,  0.5297,  2.0467, -1.6592],
         [-1.0904,  1.0526,  1.4392, -0.8564, -0.4719],
         [ 0.9377,  1.8231,  0.5933,  1.4192,  0.1107]],

        [[ 0.9682, -0.5216, -2.0017,  0.3518, -0.2546],
         [-0.1182, -0.8282,  0.1380,  1.2404,  2.2102],
         [-1.0617,  0.7063, -1.8833,  0.2697, -0.1918],
         [-1.2480,  0.0160,  1.2359,  0.1901,  0.6726],
         [ 0.1419,  0.8423,  0.5953, -1.6909, -1.6516]]])

In [83]:
test = TestConv()
y = test(x)
print(y)

tensor([[[0.1789]]], grad_fn=<ReluBackward0>)


In [86]:
image = Image.open('../dataset/0Q3A0032.JPG')

image_compose = transforms.Compose([
    transforms.Resize(32),
    transforms.ToTensor()
])
image_r = image_compose(image)
print(type(image_r))
y = test(image_r)
print(y)

<class 'torch.Tensor'>
tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]], grad_fn=<ReluBackward0>)
